### ISSUE TITLE
اشتباه ساختن قهرمان ها

### ISSUE THREAD

**Issue by ImaniAm** [SharifAIChallenge/AIC19-Server#10]
سلام. بنده تابع پیک ترنم یه خطه و کلا هیلر می سازم ولی داخل یکی از بازی های دوستانه نگهبان ساخته بودم و این خیلی عجیبه. توی یکی دیگه از بازی های دوستانه هم قراول ساخته بودم. داخل زیپ پایین کلاینت و لاگ همون بازی هستش که داخلش نگهبان می سازم. ممنون میشم اگر پیگیری بفرمایید.
[1.zip](https://github.com/SharifAIChallenge/AIC19-Server/files/2871015/1.zip)

**Comment by ImaniAm** [comment]
سلام. میشه بفرمایید نتیجه اعتراضم چی شد؟ چون ما می خواهیم بازی گروهی بکنیم و بنده منتظر پاسخ شما هستم.

**Comment by taslimisina** [comment]
سلام. در صورتی که پیام پیک ترن از طرف کلاینت به سرور نرسه یا اشتباه برسه، سرور یک هیرو به طور رندوم برای شما در نظر میگیره.
برای رفع این مشکل این کار ها رو انجام بدین:

1. مطمعن شوید که از آخرین نسخه ی سرور و کلاینت استفاده میکنین
2. مقدار تایم اوت سرور را با استفاده از کدی که در بخش readme گذاشته شده است افزایش بدید 
3. مطمعن شوید کد قسمت های پیک ترن و  preProcess شما درست باشد و مشکلی نداشته باشد

اگر این کار ها را انجام دادید و درست نشد دوباره اطلاع دهید و اگر درست شد لطفا بگویید که چه کار کردید.
با تشکر

**Comment by hamidreza004** [comment]
با چک کردن کدتون متوجه شدیم که توی 
preprocess
تایم می‌شید.

**Comment by RuhollahSeka** [comment]
در ریلیز جدید دیگر تایم شدن تاثیری در انتخاب‌های شما نخواهد داشت
