### ISSUE TITLE
سنتری و حریف در یک خونه

### ISSUE THREAD

**Issue by yektasrk** [SharifAIChallenge/AIC19-Server#12]
وقتی که سنتری و یک حریف توی یک خونه قرار می‌گیرن، سنتری خونه‌ی خودش رو که هدف می‌گیره از حریف جون کم نمی‌شه.

**Comment by taslimisina** [comment]
از فیدبکتون متشکریم.
در حال درست کردن این مشکل هستیم.

**Comment by taslimisina** [comment]
حرفی که زدید را تست کردیم و مشکلی نبود و سنتری جون حریف هم خانه اش را به درستی کم میکرد.
لطفا مطمعن شوید که هیرو ها در respawnZone نبوده باشند 
و ap کافی را دارا بوده اند و ابیلیتی دیگری استفاده نکرده باشند.
