### ISSUE TITLE
not ending game 

### ISSUE THREAD

**Issue by nimamoradi** [SharifAIChallenge/AIC19-Server#13]
بازی بعد یک ساعت هنوز می زنه در حال اجرا
![image](https://user-images.githubusercontent.com/18138551/53290973-f4b10080-37c0-11e9-948d-008b97e463b6.png)

**Comment by taslimisina** [comment]
این مشکل از سمت سرور نمیباشد.
سایت در حال اجرای دوباره ی بازی های 0-0 میباشد و تا مدتی بعد این مشکل رفع میشود
