### ISSUE TITLE
زمان ارائه نمایشگر بازی

### ISSUE THREAD

**Issue by irforghani** [SharifAIChallenge/AIC19-Server#3]
با سلام 
میخواستم بدونم نمایشگر بازی رو کی ارائه میدین . اینجوری خیلی سخته کد زدن ولی وقتی دقیق ببینیم چه اتفاقی داره میوفته خیلی بهتره

**Comment by hamidreza004** [comment]
سلام
یک الی دو روز آینده
ضمنا نگران نباشید تا پایان غیرحضوری حدود ۲۰ روز وقت باقی مونده.
