### ISSUE TITLE
server problem

### ISSUE THREAD

**Issue by kanorm** [SharifAIChallenge/AIC19-Server#4]
hi dear ...

   when i run java client in linux by external com.google.gson package i get this error from the server ..

![ee](https://user-images.githubusercontent.com/46886165/52528489-24f29c80-2cf5-11e9-98b9-ec6768432125.png)

  and this is my clinet 

![ee2](https://user-images.githubusercontent.com/46886165/52528515-d1cd1980-2cf5-11e9-9da3-fc11a73be6d2.png)

**Comment by hamidreza004** [comment]
Hi!
Your "gson" is out of date.
You can download compatible version from [https://github.com/SharifAIChallenge/AIC19-client-java](https://github.com/SharifAIChallenge/AIC19-client-java)
