### ISSUE TITLE
cant pick a hero !!! 

### ISSUE THREAD

**Issue by houshangi** [SharifAIChallenge/AIC19-Server#7]
when im trying to pick  a hero with python client  , i use this method : 

world.pick_hero(hero_name="BLASTER")

but i get the following error :
self.queue.put(Event('pick', [hero_name.value]))
AttributeError: 'str' object has no attribute 'value

P.S: i am using the latest version'

**Comment by RuhollahSeka** [comment]
you should use the enum HeroName as the input:
world.pick_hero(hero_name=Model.HeroName.BLASTER)

**Comment by houshangi** [comment]
tnx for reply , 
you should tell all users that they  can see list of all other hereos after picking phase . 
it can be declared as bug . 
thanks for your time and paitence :+1:
