### ISSUE TITLE
باگ حرکت کردن هیرو های تیم یکسان توی هم

### ISSUE THREAD

**Issue by kingk13** [SharifAIChallenge/AIC19-Server#8]
[graphic.log](https://github.com/SharifAIChallenge/AIC19-Server/files/2869095/graphic.log)
[server_view.log](https://github.com/SharifAIChallenge/AIC19-Server/files/2869094/server_view.log)

توی اول بازی هیرو های تیم ۱ به سمت هم حرکت میکنن و از توی هم رد میشن
که فکر نکنم بر اساس قانونی که توی pdf گفتید راجع به خونه های معمولی درست باشه

**Comment by ph98** [comment]
سلام
همونطوری که توی گروه گفتن بقیه ، این از توی هم رد شدن مربوط به انیمیشن موجود هست ، 
توی pdf چیزی که نوشته این هست که همزمان نمیتونن توی یک خونه باشن صرفا
از توی هم رد شدن اصلا گفته نشده و خب گفته شدنش هم مشخصا منطقی نیست
