### ISSUE TITLE
باگ مقدار برگشتی متد getPathMoveDirection

### ISSUE THREAD

**Issue by amk9978** [SharifAIChallenge/AIC19-Server#9]
این متد گاهی با وجود داشتن مسیر بین مبدا و مقصد نال برمیگردونه واندازه آرایه اش صفره
_[graphic.log](https://github.com/SharifAIChallenge/AIC19-Server/files/2870914/graphic.log)_
[server_view.log](https://github.com/SharifAIChallenge/AIC19-Server/files/2870923/server_view.log)

**Comment by RuhollahSeka** [comment]
لطفا سوالتون رو در بخش کلاینتی که استفاده میکنین بپرسین
